import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import { Providers } from "../providers";
import Loader from "@/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function PreviewLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader
          color="#633CFF"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
        />
        <Toaster position="top-right" richColors theme="system" closeButton />
        <Providers>
          <Suspense fallback={<Loader />}>
            <div>{children}</div>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
