import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center justify-center min-h-screen bg-gray-50 py-12">
          <img src="/logo.png" alt="devlinks" className="h-12 mx-auto mb-4" />

          <div className="w-full max-w-md px-8 py-10 bg-white rounded-lg shadow-md">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
